### ISSUE TITLE
Should the X(..) method resize its result argument

### ISSUE THREAD

**Issue by philippedevloo** [labmec/neopz#40]
As it is the method X of TPZGeoElRefless will resize the result. I believe the user should know the X coordinates are of size 3 and provide an argument of the proper size

**Comment by thiagoquinelato** [comment]
I agree. An assert (which should generate code only in Debug mode) should be enough.

**Comment by orlandini** [comment]
I like leaving the responsibility for the user.

While it is not exactly user-friendly, it helps identifying potential errors. See [commit d435953
](https://github.com/labmec/neopz/commit/d435953b630234ee2c4d5317a28a9cecc18f369e).
In this case, 
```gel->ProjectInParametricDomain(qsi, projection);```
returns the coordinates in the element's parametric coordinates, but
```mySide.X(projection, xclose);```
was expecting ```projection``` to be a coordinate on the side's domain.
It was only possible to easily identify this logic error because ```TPZTransform<T>::Apply``` checks (in Debug mode) if the dimensions of its parameters are correct.

**Comment by gustavobat** [comment]
I've also had a problem like Francisco's where not resizing the result helped me tracking the bug. I vote for leaving the responsability to the user as well.

**Comment by gustavobat** [comment]
I've had problems like Fran's, where resizing the vector made a previously introduced bug harder to track.  I vote for leaving the responsability to the user as well.

**Comment by philippedevloo** [comment]
Done, X requires an argument of size 3
