### ISSUE TITLE
Initialization of exact derivative matrix when post processing error needs review

### ISSUE THREAD

**Issue by gustavobat** [labmec/neopz#49]
While comparing exact errors calculated with a various thread number, @orlandini and I have stumbled upon an inconsistency that is introduced by the following line:

https://github.com/labmec/neopz/blob/667ad54472eb6dfd74487da9f71f66b7e1b62c07/Mesh/pzinterpolationspace.cpp#L1034

The number of rows in the exact derivative matrix is ```dim + 1``` and its elements are not initialized.

In materials such as ```TPZMatLaplacian```, the error computation iterates according to its dimension for the energy norm:
https://github.com/labmec/neopz/blob/30686f7bbfeb402d40bc204012ea0077cae31d58/Material/TPZMatLaplacian.cpp#L773

But not for the H1 semi norm:
https://github.com/labmec/neopz/blob/30686f7bbfeb402d40bc204012ea0077cae31d58/Material/TPZMatLaplacian.cpp#L768

In 2D, this implies that the user must specify a zero z-derivative in the exact solution to avoid UB, which may not be intuitive.
Also, the exact derivative matrix in 3D has 4 rows.

We, thus, propose the following discussion:
1. With which dimensions should du_exact be created in pzinterpolationspace.cpp?
2. Should it be initialized (filled with zeros)?
These two topics can be solved immediately, but we would like to use this opportunity for deciding upon the expected behaviour of the materials included in the library. Are all materials supposed to work for problems set in 2D manifolds in a 3D domain?

**Comment by orlandini** [comment]
I would like to propose a solution.
in ```pzinterpolationspace.cpp```, `u_exact` and `du_exact` would be initialised as follows:
```
//int ndof = material->NStateVariables(); no longer needed
//int nflux = material->NFluxes(); no longer needed
uint64_t u_len=0, du_row = 0, du_col = 0;
material->GetSolutionDimensions(u_len,du_row,du_col)
TPZManVector<STATE,10> u_exact(u_len);
TPZFNMatrix<9,STATE> du_exact(du_row,du_col);
```

Therefore, delegating to the `TPZMaterial` instance the task of getting the correct dimensons of the expected solution. This would add a degree of freedom (no pun intended) in respect to whether the solution of a 2D problem resides in a 3D or 2D space. I would also propose the definition of
```
TPZMaterial::GetSolutionDimensions(uint64_t u_len, uint64_t du_row, uint64_t du_col)
{
  u_len = 1;
  du_row = 3; //or fDim?
  du_col = 1;
}
```

to be conforming with H1 problems, which I would assume to be the "default" usage of the library. It would remain to be decided whether the default implementation would set `du_row=fDim` or `du_row=3`.

**Comment by philippedevloo** [comment]
I suggest to make the first dimension of du_exact equal 3 (spatial dimension of the library) AND initialise its 
members with zero.

Not initialising the values with zero was a “stupid” optimisation...

**Comment by orlandini** [comment]
@philippedevloo ok, so definitely initialising `u_exact` and `du_exact`.do you see any cons on delegating the responsability to the `TPZMaterial` instance as I suggested?

I am worried about materials that require unusual solutions (maybe more than one state variable, or a tensor derivative, etc). In this scenario, either the exact solution would need to resize the data structures or the material would need to. In any case, by just setting the first dimension of `du_exact` to 3, that would happen at each integration point. That's why I proposed adding a method to the materials to initialies the structures already with the appropriate dimensions.

**Comment by philippedevloo** [comment]
In fact yes. There are already to many interface associated with TPZMaterial…

If TPZAnalyticSolution would return an std::function object, would this solve some issues?
The function can resize the data structures internally...

Philippe Devloo
phil@fec.unicamp.br

**Comment by orlandini** [comment]
>  If TPZAnalyticSolution would return an std::function object, would this solve some issues?

Not that I can see. If I understood what you mean, as of now, the data structures can already be resized internally as in, e.g.,
```
static void DummyExactSolution(const TPZVec <REAL> &pt, TPZVec <STATE> &sol, TPZFMatrix <STATE> &solDx) {
  sol.Resize(1);
  solDx.Resize(3,1);
  const auto x = pt[0], y = pt[1];
  sol[0] = std::sin(2 * M_PI * x) * std::sin(2 * M_PI * y);
  solDx(0, 0) = 2 * M_PI * std::cos(2 * M_PI * x) * std::sin(2 * M_PI * y);
  solDx(1, 0) = 2 * M_PI * std::sin(2 * M_PI * x) * std::cos(2 * M_PI * y);
  solDx(2, 0) = 0;
}
```
but, still, that would still result in calls to `TPZManVector<STATE>::Resize` and `TPZFNMatrix<STATE>::Resize` at each integration point. Speculating a bit on how much the compiler would be able to optimise, the first call can at most be reduced to one comparison and the second two comparisons (considering that `Rows()` and `Cols()` would be indeed inlined, which I think would be the case).

 > There are already to many interface associated with TPZMaterial

I agree. Too many of these interfaces, in my opinion, could be eliminated, since many of those are only meant to be used in the internal parts of the library. This new proposed interface, on the other hand, would be aimed for the user (or anyone writing a new class with different approximation spaces). It could probably even be inlined by the compiler as well.

**Comment by orlandini** [comment]
@philippedevloo has approved the creation of a `TPZMaterial::GetSolutionDimensions` method. This approval was conditioned to a cleanup of `TPZMaterial` interfaces.

I have one question regarding its implementation.

I had proposed implementing it as a virtual method with the following definition:
```
TPZMaterial::GetSolutionDimensions(uint64_t u_len, uint64_t du_row, uint64_t du_col)
{
  u_len = 1;
  du_row = 3; //or fDim?
  du_col = 1;
}
```

and any classes that would need different parameters could override it. However, setting all the dimensions to zero in the base class definition and catching a out of bounds exception on 

https://github.com/labmec/neopz/blob/30686f7bbfeb402d40bc204012ea0077cae31d58/Mesh/pzinterpolationspace.cpp#L1140

we could force the user on implementing the method on the derived class.

Any thoughts on that?

@philippedevloo has also suggested that this whole exact solution section could be moved from `TPZAnalysis` to `TPZMaterial`, and this is also something interesting to think about...
